### ISSUE TITLE
massastation compatibility not checked with the plugin

### ISSUE THREAD

**Issue by Pierregvx** [massalabs/station-massa-wallet#504]
**Context**
There is no check to see if massastation is compatible with the plugin for :
- an install from the store 
- when we launch a plugin

**User flow**
use an old version of massastation
install a plugin in the store 
you should get some errors when trying to access the plugin

**How to**
 we can add a field isCompatible in the store struct that return false if the plugin cannot be installed and remove the plugin from the list of the store or display a warning in the frontend 

**Technical details**
The check if the install is available could be similar to the one for the update 

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

_Originally posted by @Pierregvx in https://github.com/massalabs/station-massa-wallet/issues/494#issuecomment-1623094075_

**Comment by SlnPons** [comment]
Let's make sure to cover all the possible use cases for this point: 
Use case 1: As a user, I want to install a plugin using the store.
1. I go to Massa Station store 
2. I see the plugin listed 
3. I click on download 
--> if the version of massa station listed in the store under `massaStationVersion` is incompatible; we don't prevent the installation. Because this field is not checked during the installation. 

Use case 2: As a user, I already have installed a plugin and I an update is available.
1. I go to Massa Station store
2. I see the update available on my station
3. I click on the update button.
--> if the version of massa station is incompatible with the one listed on the store under `massaStationVersion`. What is happening currently? 

@Pierregvx could you check both cases above please? 
Also if you think about other use case, feel free to add them.

**Comment by Pierregvx** [comment]
> Let's make sure to cover all the possible use cases for this point: Use case 1: As a user, I want to install a plugin using the store.
> 
> 1. I go to Massa Station store
> 2. I see the plugin listed
> 3. I click on download
>    --> if the version of massa station listed in the store under `massaStationVersion` is incompatible; we don't prevent the installation. Because this field is not checked during the installation.
yes
> Use case 2: As a user, I already have installed a plugin and I an update is available.
> 
> 1. I go to Massa Station store
> 2. I see the update available on my station
> 3. I click on the update button.
>    --> if the version of massa station is incompatible with the one listed on the store under `massaStationVersion`. What is      > happening currently?
the update won't be proposed to the user if it is not compatible 

Use case 3 :
1: a plugin is installed but massastation is deprecated
2: click on the link to the plugin 
 --> we are not sending any warning
> @Pierregvx could you check both cases above please? Also if you think about other use case, feel free to add them.

**Comment by longgamma-massa** [comment]
The decision we took with @Pierregvx is:

If a plugin is not compatible with the current version of Massa station installed, but requires a newer version, we:

1. hide the download button and display a warning message:
"Available in the version {version number}".

@Pierregvx will make a followup task for the frontend.
CC @gregLibert

**Comment by Pierregvx** [comment]
I posted this issue is in the wrong repository
