### ISSUE TITLE
Encode salt as base64 on wallet encryption

### ISSUE THREAD

**Issue by Eitu33** [massalabs/station-massa-wallet#551]
## Context

To respect the recommended practices in [PHC string format specification](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md#function-duties), the 16 salt bytes must be base64 encoded (resulting in 22 chars) before encryption in the massa-station wallet. Decryption must also handle the new salt format.

## Related work & additional information

https://github.com/massalabs/massa-standards/pull/111
https://github.com/massalabs/massa/pull/4044#issuecomment-1653874101

**Comment by longgamma-massa** [comment]
@gregLibert @Eitu33 @Thykof is this still relevant?

**Comment by Eitu33** [comment]
I do not think so but I stopped following this matter, let's wait for confirmation before we close it

**Comment by gregLibert** [comment]
> @gregLibert @Eitu33 @Thykof is this still relevant?

From my understanding we can. @litchipi can you confirm?

**Comment by litchipi** [comment]
Following the discussion here: https://github.com/massalabs/massa-standards/pull/111

The base64 encoding recommendation is just for convenience, it's not security-related, so it's not a a problem to leave it as a list of numbers.
Instead of changing the specification, and modify the code everywhere, we keep the same format, and on `massa` side the code is adapted. (See https://github.com/massalabs/massa/pull/4044/files#diff-f763df95cf27eb9f0f7172c218b74ac7ffc6bc690855150aa2b255827a395fd4R23)

So we can close this
