### ISSUE TITLE
Frontend Sign Call SC operation

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/station-massa-wallet#610]
**Context**
#587 main feature task

**User flow**
- User is interacting with a dApp (you can test it via Bridge product)
- dApp is requesting a user to sign the Operation 
- User should see information about the operation he is about to sign (provide a password)

**How to**
- [designs](https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=5237-27232&mode=design&t=mX2n36EmUpo1kKx1-0) (need validation after tech eval)

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by longgamma-massa** [comment]
@mazmassa @pivilartisant here's the issue for frontend only :)

**Comment by pivilartisant** [comment]
@longgamma-massa and @Thykof I see that this issue is present on station-massa-wallet and we are talking about using it in the bridge app, can you confirm that this front end component will be used accross multiple apps ? 
cc @mazmassa

**Comment by Thykof** [comment]
no this frontend component is on wallet only. The user flow to see this component has multiple software entry point: whenever you sign a call sc operation

**Comment by pivilartisant** [comment]
Update on the task : We (@mazmassa  and I) have encountered a hard blocker for this screen :  the original front was not made to change sizes and is not (at all) scalable or modifiable. 

The main problem is that all the logic is in one file... it is far from the standards we have now. Sadly everything seems linked together so it’s not like we could simply extract logic, because one component is used for 4 different types of operations… and this component receives comes from functions inside it.

I will continue what I can with the screen today, get the front as close to done as possible but we will need to refactor some code on the wails side before going forward & being able to merge (this will probably be done next week).

**Comment by pivilartisant** [comment]
Update : This is now part of a larger task that will feature the 5 different variations of these screens 
cc @longgamma-massa

**Comment by pivilartisant** [comment]
Update : will now start implementing FE Sign Call SC with & without description
